### PR TITLE
Upgradeable Proxy Factory

### PR DESCRIPTION
**Pull request by bonedaddy**
Contains modifications to the `upgradeable` branch

# TODO

* Figure out how to deploy the CashV2Test contract from within tests, right now I'm deploying through migrations although I dont think this is the best option

### CODE REVIEW

**Review by kallolborah — COMMENTED** [review]
@bonedaddy changes look good to me. I have only three observations :
1. what really is the use of tokenfactory, cashfactory, bondfactory ? I see a comment about avoiding 'admin fallback errors' but I don't get it.
2. the last test in cash added 'ViaUSDUpgrade' should have a few logs like the ViaUSD issue test case that can show balance of the account after ether is sent. Perhaps, you can copy a couple of relevant logs from the first test case and add it there.
3. we also ought to have a separate deployment script (like 3_upgrade_contracts.js' to upgrade select contracts. This can do upgradeTo, same as what you are doing in the additional test case. Otherwise, you can also check if we can use upgrades plugin to upgrade individual contracts. We have been anyway advised to use upgrades plugin to check upgrade safety of contracts before we deploy new versions of contracts.

**Comment by bonedaddy** [comment]
> what really is the use of tokenfactory, cashfactory, bondfactory

They're implementations of upgradeable proxy factories for the Token, Cash, and Bond contracts. Essentially to do this the factory needs access to the creation code for contracts, which is only available at compile time. 

>  I see a comment about avoiding 'admin fallback errors' but I don't get it.

I'm not sure what you are talking about? Could you link to the line in the file

> the last test in cash added 'ViaUSDUpgrade' should have a few logs like the ViaUSD issue test case that can show balance of the account after ether is sent. Perhaps, you can copy a couple of relevant logs from the first test case and add it there.

Yes good Idea

> we also ought to have a separate deployment script (like 3_upgrade_contracts.js' to upgrade select contracts. This can do upgradeTo, same as what you are doing in the additional test case. Otherwise, you can also check if we can use upgrades plugin to upgrade individual contracts. We have been anyway advised to use upgrades plugin to check upgrade safety of contracts before we deploy new versions of contracts.

Good idea, I will try out using the upgrades plugin since it *should* work for upgrading just not deployment.

**Review by kallolborah — APPROVED** [review]
@bonedaddy I think we should remove references to CashV2Test from deployment migration script and cash testjs ? Or do we have the reference for running the upgrade test in cash testjs ? In that case, best is to move CashV2Test.sol to the test folder in the project ?

**Comment by kallolborah** [comment]
@bonedaddy can you also perhaps create the PR to merge upgradeable to master branch ? Master has pausable, etc changes which we do not have in upgradeable. I think master is ahead by upgradeable by a few commits but behind by a lot.

**Comment by bonedaddy** [comment]
> I think we should remove references to CashV2Test from deployment migration script and cash testjs ? 

We should remove from the migration script but not from the test, since the test makes sure we can upgrade cash and it still works.

> can you also perhaps create the PR to merge upgradeable to master branch ? Master has pausable, etc changes which we do not have in upgradeable. I think master is ahead by upgradeable by a few commits but behind by a lot.

Yup

**Pull request merged**
